### ISSUE TITLE
common response

### ISSUE THREAD

**Issue by tddudwns1** [tddudwns1/base_practice#4]
## 🚧 Description
공통 응답 객체 만들자~

## ✅ Todo
- [ ] global exception handler 만들기
- [ ] business exception 만들기
- [ ] custom result response 만들기
- [ ] custom result code 만들기
- [ ] global error response 만들기
- [ ] global error code 만들기

## 🛠️Etc
https://adjh54.tistory.com/79
https://adjh54.tistory.com/89
